name: Get Tweets

on:
  schedule:
    - cron: "30 5 * * *"

jobs:
  get-tweets:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 16.15.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run
        run: npm run tweets-data

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update tweet data."
